### ISSUE TITLE
Unable to use proceedWithApplePay method Money Hash Flutter SDK v2.0

### ISSUE THREAD

**Issue by murtuza-kitopi** [MoneyHash/moneyhash-flutter-example#2]
**Describe the bug**
Money hash flutter SDK 2.0 introduces a new method `proceedWithApplePay` to be sued for Apple pay. The problem is that the deposit amount it takes is Float which can't be constructed in flutter.

Please refer to the screenshot attached for more details.

**To Reproduce**
1. Add money hash flutter package (v 2.0) to any Flutter application
2. Try to integrate proceedWithApplePay by passing deposit amount as any double value as Float can't be constructed in flutter.
3. It results in a compile time error saying `The argument type 'double' can't be assigned to the parameter type 'Float'`

**Expected behavior**
To be able to integrate and call proceedWithApplePay with a double value.

**Screenshots**
<img width="829" alt="Screenshot 2024-08-21 at 8 58 28 AM" src="https://github.com/user-attachments/assets/0c5f2515-e46b-448d-82b6-0b1247145a11">

**Flutter Doctor summary**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.0, on macOS 14.5 23F79 darwin-arm64, locale en-AE)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] Connected device (5 available)
[✓] Network resources
• No issues found!

**Comment by ahmedsalemelzeiny** [comment]
Hi @murtuza-kitopi 

Thank you once again for reporting the issue. We’ve investigated it and are happy to inform you that it has been fixed. The fix is included in version 2.0.1, which has just been released.

Feel free to update and let us know if you encounter any further issues.
